/* eslint-disable camelcase */
import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import HeaderComp from './components/header'
import { ReactNode } from 'react'

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang='en'>

      <body className={`${plusJakartaSans.className} flex flex-col h-[100svh]`}>
        <HeaderComp />
        <main className='w-full h-full bg-kcianli'>
          {children}
        </main>
      </body>
    </html>
  )
}
