import React from 'react'

export const metadata = {
  title: 'Kanban APP',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
    <h2 className="text-kred">Pagina de la aplicacion</h2>
    </>
  )
}
