import React from 'react'

export const metadata = {
  title: 'Bienvenido',
  description: 'Generated by create next app',
}
export default function Start() {
  return (
    <>
    <h2 className="text-kred">Pagina de Bienvenida</h2>
    </>
  )
}
